export const menuPresetArray = [
    {
        id: 1,
        category: 'drinks',
        productName: 'Черный кофе',
        volume: 200,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 300,
        imgPath: 'menu-item-coffee-black',
        extraSettings: false,
    },
    {
        id: 2,
        category: 'drinks',
        productName: 'Эсперссо',
        volume: 200,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 700,
        imgPath: 'menu-item-coffee-espresso',
        extraSettings: false,
    },
    {
        id: 3,
        category: 'drinks',
        productName: 'Двойной эспрессо',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 1100,
        imgPath: 'menu-item-coffee-double-espresso',
        extraSettings: false,
    },
    {
        id: 3,
        category: 'drinks',
        productName: 'Американо',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 700,
        imgPath: 'menu-item-coffee-americano',
        extraSettings: false,
    },
    {
        id: 4,
        category: 'drinks',
        productName: 'Какао',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 500,
        imgPath: 'menu-item-coffee-cocoa',
        extraSettings: false,
    },
    {
        id: 5,
        category: 'drinks',
        productName: 'Капучино',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 500,
        imgPath: 'menu-item-coffee-сappuccino',
        extraSettings: false,
    },
    {
        id: 6,
        category: 'drinks',
        productName: 'Нескафе',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 400,
        imgPath: 'menu-item-coffee-nescafe',
        extraSettings: false,
    },
    {
        id: 7,
        category: 'drinks',
        productName: 'Кофе с молоком',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 450,
        imgPath: 'menu-item-coffee-with-milk',
        extraSettings: false,
    },
    {
        id: 7,
        category: 'drinks',
        productName: 'Кофе с нутеллой',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 600,
        imgPath: 'menu-item-coffee-with-nutella',
        extraSettings: false,
    },
    {
        id: 8,
        category: 'drinks',
        productName: 'Чай чёрный',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 500,
        imgPath: 'menu-item-tea',
        extraSettings: false,
    },
    {
        id: 9,
        category: 'drinks',
        productName: 'Чай фруктовый',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 400,
        imgPath: 'menu-item-tea-fruit',
        extraSettings: false,
    },
    {
        id: 10,
        category: 'drinks',
        productName: 'Чай холодный',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 350,
        imgPath: 'menu-item-tea-cold',
        extraSettings: false,
    },
    {
        id: 10,
        category: 'drinks',
        productName: 'Чай холодный',
        volume: 400,
        measure: 'мл.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 350,
        imgPath: 'menu-item-tea-cold',
        extraSettings: false,
    },
    {
        id: 11,
        category: 'pies',
        productName: 'Пирожок с картошкой',
        volume: 100,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 250,
        imgPath: 'menu-item-pie',
        extraSettings: false,
    },
    {
        id: 12,
        category: 'pies',
        productName: 'Пирожок с капустой',
        volume: 100,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 250,
        imgPath: 'menu-item-pie',
        extraSettings: false,
    },
    {
        id: 13,
        category: 'pies',
        productName: 'Пирожок с яйцом',
        volume: 100,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 350,
        imgPath: 'menu-item-pie',
        extraSettings: false,
    },
    {
        id: 14,
        category: 'pies',
        productName: 'Пирожок с мясом',
        volume: 100,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 450,
        imgPath: 'menu-item-pie',
        extraSettings: false,
    },
    {
        id: 14,
        category: 'pies',
        productName: 'Пирожок с сыром',
        volume: 100,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 450,
        imgPath: 'menu-item-pie',
        extraSettings: false,
    },
    {
        id: 15,
        category: 'salads',
        productName: 'Салат летний',
        volume: 300,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 600,
        imgPath: 'menu-item-salad-tomato',
        extraSettings: false,
    },
    {
        id: 16,
        category: 'salads',
        productName: 'Салат греческий',
        volume: 200,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 700,
        imgPath: 'menu-item-salad-greek',
        extraSettings: false,
    },
    {
        id: 17,
        category: 'salads',
        productName: 'Салат табуле',
        volume: 200,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 800,
        imgPath: 'menu-item-salad-tabule',
        extraSettings: false,
    },
    {
        id: 18,
        category: 'salads',
        productName: 'Салат Цезарь',
        volume: 200,
        measure: 'гр.',
        currency: 'у.е.',
        costPrice:0,
        sellPrice: 1000,
        imgPath: 'menu-item-salad-cezar',
        extraSettings: false,
    }
   
   
   
]